apiVersion: apps/v2
kind: Deployment
metadata:
  name: hello
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-app
        image: gcr.io/google-samples/hello-app:2.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---

apiVersion: v2
kind: Service
metadata:
  name: hello
spec:
  type: NodePort 
  selector:
   app: hello
  ports:
  - port: 80
    targetPort: 8080
